doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8

        url: '%env(resolve:DATABASE_URL)%'

        types:
            movie_id: 'App\Model\Movie\Entity\Movie\IdType'
            schedule_id: 'App\Model\Movie\Entity\Schedule\IdType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Movie:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Movie/Entity'
                prefix: 'App\Model\Movie\Entity'
                alias: Movie
